# Generated by Django 5.0.1 on 2024-02-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QUESTIONS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Survey',
            new_name='Servey',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='survey',
            new_name='servey',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='survey',
            new_name='servey',
        ),
    ]
