# Generated by Django 5.0.1 on 2024-02-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QUESTIONS', '0002_rename_survey_servey_rename_survey_question_servey_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servey',
            new_name='Survey',
        ),
    ]
