# Generated by Django 5.0.1 on 2024-02-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QUESTIONS', '0003_rename_servey_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='servey',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='servey',
            new_name='survey',
        ),
    ]
