# Generated by Django 5.0.1 on 2024-02-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUESTIONS', '0005_remove_choice_text_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'text')},
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
