# Generated by Django 5.0.1 on 2024-02-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUESTIONS', '0006_choice_text_alter_choice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='choice',
            name='text1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='text2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
