# Generated by Django 5.0.1 on 2024-02-03 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUESTIONS', '0007_alter_choice_unique_together_choice_text1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text2',
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QUESTIONS.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QUESTIONS.question')),
            ],
        ),
    ]
