# Generated by Django 5.0.1 on 2024-02-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUESTIONS', '0008_remove_choice_question_remove_choice_text1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='title_topic',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
